spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: chirp@sandboxd1732a458be34ed0a7b30af4b2cfb8ea.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    fyi.manpreet.chirp: DEBUG