spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirp@sandboxd1732a458be34ed0a7b30af4b2cfb8ea.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "https://chirp.manpreet.fyi"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "https://chirp.manpreet.fyi"